### ISSUE TITLE
Crash if window has no class and no name

### ISSUE THREAD

**Issue by keysmashes** [cboddy/i3-workspace-names-daemon#11]
Line numbers don't quite match the release version ([permalink to relevant line](https://github.com/cboddy/i3-workspace-names-daemon/blob/0546769048e08537d8e69fd277acb4c8b469ccb4/i3_workspace_names_daemon.py#L44)), but I get this crash whenever I open the Minecraft launcher:

```pytb
Traceback (most recent call last):
  File "/home/josh/bin/i3-workspace-names-daemon", line 11, in <module>
    load_entry_point('i3-workspace-names-daemon', 'console_scripts', 'i3-workspace-names-daemon')()
  File "/home/josh/src/i3-workspace-names-daemon/i3_workspace_names_daemon.py", line 176, in main
    i3.main()
  File "/home/josh/src/i3-workspace-names-daemon/venv/lib/python3.6/site-packages/i3ipc/i3ipc.py", line 716, in main
    while not self.event_socket_poll():
  File "/home/josh/src/i3-workspace-names-daemon/venv/lib/python3.6/site-packages/i3ipc/i3ipc.py", line 704, in event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/home/josh/src/i3-workspace-names-daemon/venv/lib/python3.6/site-packages/i3ipc/i3ipc.py", line 311, in emit
    s['handler'](self.conn, data)
  File "/home/josh/src/i3-workspace-names-daemon/i3_workspace_names_daemon.py", line 64, in rename
    for leaf in workspace.leaves()]
  File "/home/josh/src/i3-workspace-names-daemon/i3_workspace_names_daemon.py", line 64, in <listcomp>
    for leaf in workspace.leaves()]
  File "/home/josh/src/i3-workspace-names-daemon/i3_workspace_names_daemon.py", line 45, in get_icon_or_name
    window_class = leaf.name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

It seems moderately buggy for Minecraft to be spawning windows with neither class nor name, but crashing because of that is suboptimal.

If I get around to it, I'll submit a PR to fix this at some point.

**Comment by cboddy** [comment]
Thanks for submitting the issue; this case is now handled in the latest version; ``0.9.0``.
