### ISSUE TITLE
Dies if a window doesn't have a class

### ISSUE THREAD

**Issue by keysmashes** [cboddy/i3-workspace-names-daemon#8]
Apparently some windows don't have a class, in which case you get a crash like this as soon as you open a window:

```pytb
Traceback (most recent call last):
  File "./i3_workspace_names_daemon.py", line 129, in <module>
    main()
  File "./i3_workspace_names_daemon.py", line 125, in main
    i3.main()
  File "/home/josh/src/i3-workspace-names-daemon/venv/lib/python3.6/site-packages/i3ipc/i3ipc.py", line 716, in main
    while not self.event_socket_poll():
  File "/home/josh/src/i3-workspace-names-daemon/venv/lib/python3.6/site-packages/i3ipc/i3ipc.py", line 704, in event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/home/josh/src/i3-workspace-names-daemon/venv/lib/python3.6/site-packages/i3ipc/i3ipc.py", line 311, in emit
    s['handler'](self.conn, data)
  File "./i3_workspace_names_daemon.py", line 49, in rename
    for leaf in workspace.leaves()]
  File "./i3_workspace_names_daemon.py", line 49, in <listcomp>
    for leaf in workspace.leaves()]
  File "./i3_workspace_names_daemon.py", line 40, in get_icon_or_name
    window_class = leaf.window_class.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by kensand** [comment]
This should be a pretty easy fix, just add an 
`if leaf.window_class:`
before line 49. I'll make a commit and pull request in a few minutes.

**Comment by kensand** [comment]
Commited to my fork, pull request is in, should be all set once cboddy approves. Please test on your end @anowlcalledjosh . It works fine on mine (famous last words I know).

**Comment by cboddy** [comment]
Ah, I just hit this too, thanks for the report!

**Comment by cboddy** [comment]
This is now fixed.
